# Docker 환경 설정
server:
  port: 8086

spring:
  datasource:
    url: jdbc:postgresql://${POSTGRES_HOST:postgres-primary}:${POSTGRES_PORT:5432}/${POSTGRES_DB:stocksimulator}?currentSchema=news
    username: ${POSTGRES_USER:stocksim}
    password: ${POSTGRES_PASSWORD:stocksim123}
  data:
    mongodb:
      uri: mongodb://${MONGO_USER:stocksim}:${MONGO_PASSWORD:stocksim123}@${MONGO_HOST:mongodb}:${MONGO_PORT:27017}/${POSTGRES_DB:stocksimulator}?authSource=admin
    redis:
      host: ${REDIS_HOST:redis}
      port: ${REDIS_PORT:6379}
      password: ${REDIS_PASSWORD:stocksim123}
    elasticsearch:
      uris: http://${ELASTICSEARCH_HOST:elasticsearch}:${ELASTICSEARCH_PORT:9200}
  kafka:
    bootstrap-servers: ${KAFKA_HOST:kafka}:${KAFKA_PORT:9092}

eureka:
  client:
    service-url:
      defaultZone: http://${EUREKA_HOST:eureka-server}:${EUREKA_PORT:8761}/eureka/
  instance:
    hostname: news-service
    prefer-ip-address: false
