# Docker 환경 설정
server:
  port: 8761

spring:
  datasource:
    url: jdbc:postgresql://${POSTGRES_HOST:postgres-primary}:${POSTGRES_PORT:5432}/${POSTGRES_DB:stocksimulator}
    username: ${POSTGRES_USER:stocksim}
    password: ${POSTGRES_PASSWORD:stocksim123}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  data:
    mongodb:
      uri: mongodb://${MONGO_USER:stocksim}:${MONGO_PASSWORD:stocksim123}@${MONGO_HOST:mongo}:27017/stocksimulator?authSource=admin

eureka:
  instance:
    hostname: ${EUREKA_HOST:eureka-server}
    prefer-ip-address: false
  client:
    register-with-eureka: false
    fetch-registry: false
    service-url:
      defaultZone: http://${EUREKA_HOST:eureka-server}:${EUREKA_PORT:8761}/eureka/

logging:
  mongodb:
    enabled: ${LOGGING_MONGODB_ENABLED:true}
