# Docker 환경 설정
server:
  port: 8761

spring:
  data:
    mongodb:
      uri: mongodb://${MONGO_USER:stocksim}:${MONGO_PASSWORD:stocksim123}@${MONGO_HOST:mongo}:27017/stocksimulator?authSource=admin
  autoconfigure:
    exclude:
      - com.linecorp.kotlinjdsl.support.spring.data.jpa.autoconfigure.KotlinJdslAutoConfiguration

eureka:
  instance:
    hostname: ${EUREKA_HOST:eureka-server}
    prefer-ip-address: false
  client:
    register-with-eureka: false
    fetch-registry: false
    service-url:
      defaultZone: http://${EUREKA_HOST:eureka-server}:${EUREKA_PORT:8761}/eureka/

logging:
  mongodb:
    enabled: ${LOGGING_MONGODB_ENABLED:true}
