# Docker 환경 설정
server:
  port: 8085

spring:
  kafka:
    bootstrap-servers: ${KAFKA_HOST:kafka}:${KAFKA_PORT:9092}

eureka:
  client:
    service-url:
      defaultZone: http://${EUREKA_HOST:eureka-server}:${EUREKA_PORT:8761}/eureka/
  instance:
    hostname: scheduler-service
    prefer-ip-address: false
