version: '3.8'

services:
  jenkins:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: jenkins
    restart: unless-stopped
    privileged: true
    user: root
    ports:
      - "8090:8080"  # Jenkins UI
      - "50000:50000"  # Jenkins agent
    volumes:
      - jenkins_home:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
      - /usr/bin/docker:/usr/bin/docker
      - /usr/local/bin/docker-compose:/usr/local/bin/docker-compose
      - ../:/workspace
      - /home/gijunpark/Stock-Simulator:/deploy
    environment:
      - JAVA_OPTS=-Djenkins.install.runSetupWizard=false
      - DOCKER_HOST=unix:///var/run/docker.sock
    networks:
      - jenkins
      - stocksim-network

networks:
  jenkins:
    driver: bridge
  stocksim-network:
    external: true
    name: stock-simulator_stocksim-network

volumes:
  jenkins_home:
    driver: local
